# Generated by Django 2.1 on 2018-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('date_end', models.DateField()),
                ('url', models.URLField()),
                ('num_items', models.IntegerField()),
            ],
        ),
    ]
