# Generated by Django 2.1 on 2018-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comixology", "0002_auto_20180828_1345")]

    operations = [
        migrations.CreateModel(
            name="WishListComic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=256)),
                ("cover_url", models.URLField(blank=True)),
            ],
        )
    ]
