# Generated by Django 2.1 on 2018-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comixology", "0003_wishlistcomic")]

    operations = [
        migrations.AddField(
            model_name="sale", name="cover_url", field=models.URLField(blank=True)
        )
    ]
