# Generated by Django 2.1 on 2018-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("comixology", "0006_auto_20180830_2016")]

    operations = [
        migrations.AlterModelOptions(
            name="sale", options={"ordering": ["-date_end", "title"]}
        ),
        migrations.AddField(
            model_name="wishlistcomic",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
