# Generated by Django 2.2.3 on 2019-07-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comixology', '0007_auto_20180901_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['date_end', 'title']},
        ),
    ]
